### ISSUE TITLE
HTTPS version of the website is broken

### ISSUE THREAD

**Issue by paradite** [quanyang/quanyang.github.io#1]
Link:
https://quanyang.github.io/

Issue:
css and js files are loaded over http whereas https is expected:
![screen shot 2016-08-01 at 4 15 47 pm](https://cloud.githubusercontent.com/assets/1209810/17287630/654bcd20-5803-11e6-8d75-e6eb1f21c349.png)

Browser:
Chrome

OS:
Windows, OS X

HTTP version works fine but since your profile shows https version, I think it is good to fix it:

![screen shot 2016-08-01 at 4 15 55 pm](https://cloud.githubusercontent.com/assets/1209810/17287633/66f6b31a-5803-11e6-854a-e43d469659a7.png)

**Comment by quanyang** [comment]
Interesting, thanks will fix :)

**Comment by quanyang** [comment]
Fixed.
